stages:
  - build   #collect metrics on files
  - test   #inspect/analyze collected metrics

Collect Metrics:
  stage: build
  script:
    - echo "$CI_JOB_STAGE" > manifest.txt

#this file will store file characteristics that the 
#pipeline needs to check
  artifacts:
    paths:
      - manifest.txt
    expire_in: 30 minutes


Inspect:
  stage: test
  script:
  - test -f "manifest.txt"