stages:
  - build   # build everythin
  - test    # run tests
  - deploy  # deploy locally


before_script:
  - echo "Activating miniconda"
  - eval "$(/p/lscratchh/cdoutrix/gitlab/miniconda3/bin/conda shell.bash hook)"
  - echo "Updating conda"
  - conda update -y --all
  - echo "Activating env py3"
  - conda activate gitlab_kosh_py3
  - conda update -c conda-forge -y --all
#  - echo "Cloning sina"
#  - git clone ssh://git@cz-bitbucket.llnl.gov:7999/sibo/sina.git
  - echo "building sina"
  - cd ${HOME}/git/sina/python
  - pip install .
  - echo "Activating env py2"
  - conda deactivate
  - conda activate gitlab_kosh_py2
  - conda update -c conda-forge -y --all
  - pip install .
#  - echo "Cloning Mash extract"
#  - cd ../..
#  - git clone ssh://git@cz-bitbucket.llnl.gov:7999/ascaml/mashextract.git
  - conda deactivate

Install Kosh:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}
    - echo "Activating conda"
    - echo `pwd`
    - echo `ls -l`
    - eval "$(/p/lscratchh/cdoutrix/gitlab/miniconda3/bin/conda shell.bash hook)"
    - echo "Activating env py3"
    - conda activate gitlab_kosh_py3
    - python setup.py install
    - echo "Activating env py2"
    - conda activate gitlab_kosh_py2
    - python setup.py install
  tags:
    - quartz
    - shell


Run Tests:
  stage: test
  script:
    - echo "Activating conda"
    - eval "$(/p/lscratchh/cdoutrix/gitlab/miniconda3/bin/conda shell.bash hook)"
    - export PYTHONPATH=${HOME}/git/mashextract/tools:${PYTHONPATH}
    - echo "testing Py3"
    - echo "Activating env py3"
    - conda activate gitlab_kosh_py3
    - nosetests --with-coverage --cover-package=kosh tests
    - conda activate gitlab_kosh_py2
    - nosetests tests
#this file will store file characteristics that the 
#pipeline needs to check
  artifacts:
    paths:
      - .coverage
    expire_in: 3 hours
  tags:
    - quartz
    - shell

Produce coverage:
  stage: test
  script:
    - echo "Activating conda"
    - eval "$(/p/lscratchh/cdoutrix/gitlab/miniconda3/bin/conda shell.bash hook)"
    - export PYTHONPATH=${CI_BUILDS_DIR}/mashextract/tools:${PYTHONPATH}
    - echo "Activating env py3"
    - conda activate gitlab_kosh_py3
    - echo "Producing coverage files"
    - coverage html --omit doutriaux1
  artifacts:
    paths:
      - .coverage
      - htmlcov
    expire_in: 3 hours
  tags:
    - quartz
    - shell

Deploy to aml_cs:
  stage: deploy
  script:
    - if [ "${CI_COMMIT_BRANCH}" != "master" ] ; then exit 0; fi
    - echo "Activating conda"
    - eval "$(/p/lscratchh/cdoutrix/gitlab/miniconda3/bin/conda shell.bash hook)"
    - conda activate /usr/workspace/aml_cs/kosh/toss_3_x86_64_ib/dev
    - python setup.py install
    - cd sina/python
    - python setup.py install
    - find /usr/workspace/aml_cs/kosh/toss_3_x86_64_ib/dev/bin -type f -exec chmod g+rx  {} +
    - find /usr/workspace/aml_cs/kosh/toss_3_x86_64_ib/dev -type f -exec chmod g+r  {} +
    - find /usr/workspace/aml_cs/kosh/toss_3_x86_64_ib/dev -type d -exec chmod g+rx  {} +
    - conda deactivate
    - conda activate /usr/workspace/aml_cs/kosh/toss_3_x86_64_ib/dev.py2
    - python setup.py install
    - cd ../..
    - python setup.py install
    - find /usr/workspace/aml_cs/kosh/toss_3_x86_64_ib/dev.py2/bin -type f -exec chmod g+rx  {} +
    - find /usr/workspace/aml_cs/kosh/toss_3_x86_64_ib/dev.py2 -type f -exec chmod g+r  {} +
    - find /usr/workspace/aml_cs/kosh/toss_3_x86_64_ib/dev.py2 -type d -exec chmod g+rx  {} +
